### ISSUE TITLE
account.sha_pass_hash was deprecate 

### ISSUE THREAD

**Issue by XiaoSeee** [azerothcore/acore-api#97]
https://github.com/azerothcore/azerothcore-wotlk/pull/4827

https://github.com/azerothcore/azerothcore-wotlk/commit/485f7e76391a5bbf1af6b3219d27db721af38440

https://github.com/TrinityCore/TrinityCore/issues/25157

so ~ all the accounts api  can not be used

**Comment by Helias** [comment]
@IntelligentQuantum  what is the status of this?
